- app/Http/Controllers/Api/V1/MentorTutor/MainController.php
- app/Http/Controllers/Api/V1/Packages/ListController.php
- app/Http/Controllers/Api/V1/TimesheetController.php
- app/Http/Traits/TranslatePackageCategory.php
- app/Models/Package.php
- app/Models/TempUser.php
- app/Rules/SameGrade.php
- app/Services/Activity/ActivityDataService.php
- resources/js/components/admin/program/program_add.vue
- resources/js/pages/admin/program/program.vue
- resources/js/pages/admin/timesheet/timesheet.vue
- routes/api.php
1. updated endpoint : api/v1/user/mentor-tutors to fetch data tutor mentors from TempUser model (before straight from CRM).
2. updated create timesheet function : 
- failed to select grade on validation
> Et 51 be tutor mentor

- app/Actions/Authentication/CheckEmailMentorTutorAction.php
- app/Http/Controllers/Api/V1/MentorTutor/MainController.php
- app/Models/TempUser.php
- app/Services/User/CreateTempUserService.php
- database/migrations/base/2024_06_07_034903_create_base_schema.php
added phone number into list tutor mentor.
before deploy:
1. please add 1 column after email in temp_user as varchar(20)
2. run php artisan sync:tutor-mentor
> ET-61 feat: added phone number into list tutor mentor

- app/Actions/Authentication/CheckEmailMentorTutorAction.php
1. add has_npwp column when login as tutor
> feat: updated has_npwp column

- app/Http/Controllers/Api/V1/Programs/ListController.php
1. Sorting of list program changed to newest invoice
> feat: updated sorting list program

- app/Actions/Mentees/FetchMenteesAction.php
- app/Http/Controllers/Api/V1/Mentee/MainController.php
- app/Http/Controllers/Api/V1/Request/MainController.php
- app/Http/Controllers/Api/V1/Timesheet/MainController.php
- app/Http/Requests/Timesheet/StoreRequest.php
- app/Models/Ref_Program.php
- routes/api.php
> added list of mentees

- app/Actions/Mentees/FetchMenteesAction.php
- app/Http/Controllers/Api/V1/Mentee/MainController.php
- routes/api.php
1. updated fetch mentees action. send with parameter mentor uuid (k)
> feat: updated fetch mentees action

- app/Http/Requests/Request/StoreRequest.php
1. update rules of store request validation
> feat: updated store request

- app/Http/Controllers/Api/V1/Timesheet/MainController.php
- app/Models/Timesheet.php
- app/Providers/AppServiceProvider.php
- app/Services/Timesheet/TimesheetDataService.php
1. added engagement type field in list and detail of timesheet
> feat: added engagement type on list timesheet and detail

- app/Services/Timesheet/TimesheetDataService.php
> feat: updated list timesheet

- app/Services/Timesheet/TimesheetDataService.php
1. add engagement_type field in list of timesheet
> add engagement type in list timesheet

- app/Services/Timesheet/TimesheetDataService.php
1. fix engagement type not appear
> feat: updated detail of timesheet

- app/Http/Controllers/Api/V1/Activity/MainController.php
- app/Services/Timesheet/TimesheetDataService.php
1. update detail timesheet
2. update store activity
> feat: updated store activity & timesheet detail

- app/Models/TempUser.php
1. update tempUser onSearch  > tukar kondisi roles first.
> get external mentor

- app/Actions/Request/CancelRequestAction.php
- app/Http/Controllers/Api/V1/Request/MainController.php
- app/Http/Requests/Request/UpdateRequest.php
- app/Models/Ref_Program.php
- database/migrations/base/2025_02_20_114219_add_columns_to_table.php
- routes/api.php
> Staging ext mentor be

- app/Http/Controllers/Api/V1/Request/MainController.php
- database/migrations/base/2025_02_20_114219_add_columns_to_table.php
1. update request list for admin POV
> update request list pov admin

- app/Models/Ref_Program.php
> feat: updated oncancel

- app/Http/Controllers/Api/V1/Request/MainController.php
1. add cancelled param to list of request
> update list of request with cancelled param

- app/Exports/PayrollExport.php
- app/Http/Controllers/Api/V1/Timesheet/MainController.php
- app/Services/Timesheet/TimesheetDataService.php
> update store timesheet

- app/Http/Controllers/Api/V1/Timesheet/MainController.php
- app/Http/Requests/Timesheet/StoreRequest.php
1. fix tax not stored when creating a timesheet.
> feat: updated tax not saved

- app/Http/Controllers/Api/V1/Request/MainController.php
- app/Models/Ref_Program.php
1. fix scope onCancel on refProgram
> feat: on cancel scope

- app/Actions/Activity/CreateActivityAction.php
1. update tax on create activity action
> updated tax on create activity action

- routes/api.php
> add rate limit

- app/Actions/Activity/CreateActivityAction.php
- app/Http/Controllers/Api/V1/Activity/MainController.php
1. createactivityaction update
> feat: updated create activity action

- app/Services/Timesheet/TimesheetDataService.php
1. add curriculum name inside timesheet detail
> add curriculum name inside timesheet detail

- app/Console/Kernel.php
1. Add sync:free-trial-program to Kernel
> add sync free trial to kernel

- database/factories/TempUserRolesFactory.php
- database/seeders/TempUserSeeder.php
1. create factory for external mentor
> add seeder for external mentor

- app/Console/Kernel.php
- database/factories/TempUserRolesFactory.php
- database/seeders/TempUserSeeder.php
1. Create factory for external mentor
> Staging ext mentor

- app/Models/Pivot/PivotTimesheet.php
- app/Models/Ref_Program.php
- app/Models/Timesheet.php
- app/Services/Timesheet/CreateTimesheetService.php
- database/migrations/2025_03_19_090939_create_pivot_timesheets_table.php
1. update feature ref_program can have multiple timesheet
> update multiple timesheet for sat

- app/Services/Timesheet/TimesheetDataService.php
1. update on show detail timesheet for secondary timesheet
> feat: updated show detail timesheet for secondary timesheet

- app/Actions/Activity/CreateActivityAction.php
- app/Models/Timesheet.php
- app/Services/Timesheet/TimesheetDataService.php
1. Create new attribute for reference_program so that it would be easy for developers to call the ref program either they're ref_program or second_ref_program by calling reference_program.
> feat: updated post activity for secondary timesheet

- config/logging.php
1. update permission on config logging
> update config log

- app/Models/Timesheet.php
- app/Services/Timesheet/TimesheetDataService.php
1. Edited file Timesheet on ScopeOnSearch : in order to find student_name based on second_ref_program
> edited scope onSearch timesheet
